=== Opetushallitus/rajapinnat/tiedonsiirto/src/main/resources/toinenaste/perusopetusArvosanat.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat"
           xmlns="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat"
           xmlns:common="http://service.henkilo.sade.vm.fi/types/common"
           xmlns:koodisto="http://service.koodisto.sade.vm.fi/types/koodisto"
           elementFormDefault="qualified">

    <xs:import namespace="http://service.henkilo.sade.vm.fi/types/common" schemaLocation="common.xsd"/>
    <xs:import namespace="http://service.koodisto.sade.vm.fi/types/koodisto" schemaLocation="common_koodisto.xsd"/>

    <xs:element name="ROWSET">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="VUOSI" minOccurs="1" maxOccurs="1" type="common:VUOSI"/>
                            <xs:element name="KAUSI" minOccurs="1" maxOccurs="1" type="koodisto:kausi"/>
                            <xs:element name="LAHTOKOULU" minOccurs="1" maxOccurs="1" type="koodisto:oppilaitosnumero"/>
                            <xs:element name="LUOKKA" minOccurs="1" maxOccurs="1" type="common:LUOKKA"/>
                            <xs:element name="LUOKKATASO" minOccurs="1" maxOccurs="1" type="common:LUOKKATASO"/>
                            <xs:element name="HETU" minOccurs="1" maxOccurs="1" type="common:HETU"/>
                            <xs:element name="TODISTUS" minOccurs="1" maxOccurs="1" type="common:TODISTUS"/>
                            <xs:element name="AINE" minOccurs="1" maxOccurs="1" type="common:AINE"/>
                            <xs:element name="KIELI" minOccurs="0" maxOccurs="1" type="koodisto:kieli"/>
                            <xs:element name="TYYPPI" minOccurs="1" maxOccurs="1" type="common:TYYPPI"/>
                            <xs:element name="ARVOSANA" minOccurs="1" maxOccurs="1" type="common:ARVOSANA_4_10"/>
                            <xs:element name="ERA" minOccurs="1" maxOccurs="1" type="common:ERA"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Opetushallitus/rajapinnat/tiedonsiirto/src/main/resources/toinenaste/perusopetusArvosanat.xml
<?xml version='1.0' encoding='UTF-8'?>
<ROWSET xmlns="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat perusopetusArvosanat.xsd">
    <ROW>
        <VUOSI>2013</VUOSI>
        <KAUSI>S</KAUSI>
        <LAHTOKOULU>05536</LAHTOKOULU>
        <LUOKKA>9A</LUOKKA>
        <LUOKKATASO>9</LUOKKATASO>
        <HETU>111193-111V</HETU>
        <TODISTUS>1</TODISTUS>
        <AINE>A1</AINE>
        <KIELI>FI</KIELI>
        <TYYPPI>B</TYYPPI>
        <ARVOSANA>10</ARVOSANA>
        <ERA>PKERA3_2013S_05536</ERA>
    </ROW>
</ROWSET>
